### ISSUE TITLE
Не работает поиск серий сериалов

### ISSUE THREAD

**Issue by antonsoroko** [Nemiroff/script.quasar.nova#2]
```
03:44:02.053 T:18446744072397781360   ERROR: [script.quasar.nova] Traceback (most recent call last):
03:44:02.054 T:18446744072397781360   ERROR: [script.quasar.nova]   File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/plugin.video.quasar/resources/site-packages/quasar/provider.py", line 167, in register
03:44:02.055 T:18446744072397781360   ERROR: [script.quasar.nova]     objects = method(payload["search_object"])
03:44:02.057 T:18446744072397781360   ERROR: [script.quasar.nova]   File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/script.quasar.nova/burst.py", line 16, in search_episode
03:44:02.058 T:18446744072397781360   ERROR: [script.quasar.nova]     return search(payload, 'episode')
03:44:02.059 T:18446744072397781360   ERROR: [script.quasar.nova]   File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/script.quasar.nova/burst/burst.py", line 58, in search
03:44:02.060 T:18446744072397781360   ERROR: [script.quasar.nova]     payload['titles'] = dict((k.lower(), v) for k, v in payload['titles'].iteritems())
03:44:02.061 T:18446744072397781360   ERROR: [script.quasar.nova] AttributeError: 'NoneType' object has no attribute 'iteritems'
03:44:02.062 T:18446744072397781360   ERROR: [script.quasar.nova]
```
полный лог https://paste.ubuntu.com/p/Mqqn9VJZyX/

спасибо!

P.S. ещё в настройках проскакивает имя elementum (https://github.com/Nemiroff/script.quasar.nova/blob/3c9a78318e1b7199df5eb804091827f4e0916084/resources/language/messages.pot#L151), хотя в коде много где, может так проще для портирования в quasar.

**Comment by Nemiroff** [comment]
В 20 версии должно быть поправлено.

**Comment by antonsoroko** [comment]
работает, спасибо!

**Comment by antonsoroko** [comment]
@Nemiroff 
Здравствуйте. Что-то на Kodi 17 (spmc 17.6) не хочет обновляться плагин, пишет что в репе 19ая версия. Это у меня косяк или в репе? Спасибо.

**Comment by Nemiroff** [comment]
Переделывал скрипт для репо, и в релизе забыл поменять номер. Проверяйте
